// The point of this file.
//
// These are the SAME vectors the Python implementation is held to, generated by
// Python, verified here by an implementation that shares no code with it. If
// both pass, the spec is real and the format is the standard rather than
// whichever library you happened to install.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";

import { canonical, canonicalBytes } from "../src/canonical.js";
import { ser, MAX_TOTAL } from "../src/caveats.js";
import { Token, mint, verifySig, canonicalRequest } from "../src/token.js";
import { signQuote } from "../src/protocol.js";

const V = JSON.parse(readFileSync(new URL("../../spec/vectors.json", import.meta.url)));
const rootKey = Buffer.from(V.inputs.root_key_hex, "hex");
const digest = o => createHash("sha256").update(canonicalBytes(o)).digest("hex");

test("caveat serialisation is byte-stable across languages", () => {
  assert.equal(ser(MAX_TOTAL, 50_000_000), V.canonical_caveats[0]);
  assert.equal(V.canonical_caveats[2],
    'rate:{"max_amount":20000000,"max_count":4,"window_s":60}');
});

test("integral values never gain a decimal point", () => {
  // The bug this catches: Python emits 1800000000.0, JS emits 1800000000.
  assert.equal(V.canonical_caveats[3], "expires:1800000000");
  assert.equal(canonical({ expires: 1800000000 }), '{"expires":1800000000}');
});

test("canonical encoder refuses floats rather than guessing", () => {
  assert.throws(() => canonical({ x: 1.5 }), /floats are not allowed/);
});

test("non-ASCII is raw UTF-8, not escaped", () => {
  // The other bug: Python's ensure_ascii=True would emit ง... here.
  assert.equal(ser("note", "งบวิจัย café 🔒"),
    V.canonical_unicode_note);
});

test("root token signature chain", () => {
  const t = mint(rootKey, "acme", "tok_root", V.inputs.binding_root, V.canonical_caveats);
  assert.deepEqual(t.toJSON(), V.token_root);
  assert.ok(verifySig(rootKey, t));
});

test("delegated token signature, lineage and scope", () => {
  const root = Token.fromJSON(V.token_root);
  const child = root.delegate("tok_child", V.inputs.binding_child,
    [ser(MAX_TOTAL, 5_000_000)]);
  assert.deepEqual(child.toJSON(), V.token_child);
  assert.deepEqual(child.lineage, V.child_lineage);
  assert.deepEqual(child.scoped(), V.child_scoped);
  assert.ok(verifySig(rootKey, child));
});

test("a caveat cannot be removed", () => {
  const root = Token.fromJSON(V.token_root);
  const stripped = new Token(root.root_id, root.root_token_id,
    root.caveats.filter(c => !c.startsWith("max_per_tx")), root.sig);
  assert.equal(verifySig(rootKey, stripped), false);
});

test("canonical request string", () => {
  assert.equal(
    canonicalRequest("tok_child", "api.search", 2_000_000, "research", "run/1"),
    V.canonical_request);
});

test("quote signature", () => {
  assert.equal(signQuote(Buffer.from(V.inputs.merchant_key_hex, "hex"), V.quote_payload),
    V.quote_sig_hmac_sha256);
});

test("receipt hash chain", () => {
  let prev = "genesis";
  for (const row of V.receipt_chain) {
    const { hash, ...body } = row;
    assert.equal(row.prev_hash, prev);
    assert.equal(digest(body), hash);
    prev = hash;
  }
});

test("tampering a receipt breaks its hash", () => {
  const { hash, ...body } = V.receipt_chain[0];
  body.amount += 1;
  assert.notEqual(digest(body), hash);
});
